### ISSUE TITLE
cdCommand test needs extension for filtered decklists

### ISSUE THREAD

**Issue by Lessthanfree** [CS2103-AY1819S1-T09-2/main#126]
Somehow the test case fails. Currently disabled. May consider wait for implementation of find() or some filter command.

Related to #125

**Comment by truongthanh2606** [comment]
The first line in the method: "showDeckAtIndex(model, INDEX_FIRST_DECK);" would modify the filteredDeckList of model.
The actual ChangeDeckCommand would not modify the filteredDeckList, thus this test fails
Fix: Delete this line
