### ISSUE TITLE
As a user, I want to schedule my cards so that the cards I can prioritise the cards that I am weaker at

### ISSUE THREAD

**Issue by yujiatay** [CS2103-AY1819S1-T09-2/main#127]

**Comment by leeyjjoel** [comment]
I intend to use the Supermemo algorithm to implement this feature: https://www.supermemo.com/english/ol/sm2.htm 

We can use four levels instead of five(since we have four buttons) and we can label  each card with an E-Factor. On a daily basis, we can then reorder or hide cards as needed
