### ISSUE TITLE
Current implementation to block cd-undo will break undo chain

### ISSUE THREAD

**Issue by Lessthanfree** [CS2103-AY1819S1-T09-2/main#203]
User is unable to undo anything before any `cd` command as the current solution to the cd-undo bug blocks any undo operation on `cd`.

Related to #201 

**Problem:** Undo/redo works by capturing the current `Anakin` state every time another command is executed and storing it in an Array. Calling undo or redo will replace the current `Anakin` with a captured version from the Array. 
This assumes that the entire `Anakin` is immutable, however the current implementation of `cardlist` in `Anakin` is a mutable structure. This creates a problem when the cardlist is modified without the intention of changing it permanently. Most notably, when a `cardlist `is cleared via an `undo` following a `cd` command, the `cardlist `of that deck is erased permanently (See #191). 

Potential Solution(s):
**Implement immutable Anakin:** Every time `Anakin` is committed, create an deep clone of `Anakin` to be stored in the `VersionedAnakin` StatePointer.

Attempted Solutions:
**Implement immutable decks:** Cards lists cannot be edited directly. Any Card update operation must go through the Deck. Any time a Deck or its Cards are updated, create and return a new Deck to Anakin.
Problem: Creating a new Deck will break the link between Anakin's `decklist` and the Deck, meaning to say no deck changes will be permanent.

**Comment by truongthanh2606** [comment]
I suggest disabling `undo` for `cd` and `cd ..` commands because they're basically the opposite of each other. So instead of undoing, user can just `cd` to undo `cd ..` and vise versa.
