### ISSUE TITLE
Multiple arguments: List for all commands or only for specific commands

### ISSUE THREAD

**Issue by leeyjjoel** [CS2103-AY1819S1-T09-2/main#237]
Hi all,

It seems that we receive multiple bug reports of the form <Command> Supports multiple arguments.
The solution I currently have is to only accept the last valid argument for each field(i.e. if the command ```newdeck /n bob /n john``` a new deck with the name john will be created. However, it seems that we have the option of declaring at the start of the user guide that all commands will only accept the last valid argument or specifying this for each individual command. 

The former would allow us to cover all commands but at the same time create difficulties when trying to do checks. The latter could potentially  cause us to miss out some commands. What do you guys think? Happy to hear your thoughts on this issue.

**Comment by Lessthanfree** [comment]
Oh I thought this was a feature. I implemented several Parser tests to reflect this behavior. 
I think we should update the UserGuide instead of changing functionality.

**Comment by truongthanh2606** [comment]
Update User guide will do
