### ISSUE TITLE
Increase coverage to ~90%

### ISSUE THREAD

**Issue by truongthanh2606** [CS2103-AY1819S1-T09-2/main#246]

**Comment by truongthanh2606** [comment]
Expectation on test code - set by Damith

**Comment by leeyjjoel** [comment]
Hi @truongthanh2606 sure. I'm currently working on it

**Comment by truongthanh2606** [comment]
I'll work on increase coverage of existing classes: ModelManager, Anakin, EditCardCommand, Parser

**Comment by leeyjjoel** [comment]
Hey @truongthanh2606 that's great. However, I'm currently working on EditDeckCommand and I'm about to finish the tests for it. Please leave that particular class out of your tests until I finish. Thanks!

**Comment by yujiatay** [comment]
Hey, I can help out with this too. I'll focus on improving coverage for **review**-related files. Will update you guys with the exact list after I look at the code.

**Comment by truongthanh2606** [comment]
> Hey @truongthanh2606 that's great. However, I'm currently working on EditDeckCommand and I'm about to finish the tests for it. Please leave that particular class out of your tests until I finish. Thanks!

Sure

**Comment by yujiatay** [comment]
I have added tests for FlipCardCommand, ClassifyCommand and DeckReviewCard and also removed BrowserPanel in my recent PR #250
