### ISSUE TITLE
Add support in AnakinModelManager to change isInsideDeck state of Anakin

### ISSUE THREAD

**Issue by Lessthanfree** [CS2103-AY1819S1-T09-2/main#59]
Currently there is no way to change isInsideDeck without accessing the Anakin object directly. AnakinModelManager should have a method to modify isInsideDeck. Also AnakinModel interface should reflect this.

Required to implement #52

**Comment by yujiatay** [comment]
PR is not merged yet

**Comment by Lessthanfree** [comment]
Merged
